### ISSUE TITLE
Titleコンポーネントの修正

### ISSUE THREAD

**Issue by ishiki11** [Kozaki01/2023_04_cteam#57]
画面表示にあうように修正する

**Comment by Kozaki01** [comment]
作ったもの
![スクリーンショット 2023-07-11 120903](https://github.com/Kozaki01/2023_04_cteam/assets/101164560/e70da602-7c05-4d4a-a3c4-0848383176e3)

figmaのもの
![スクリーンショット 2023-07-11 121535](https://github.com/Kozaki01/2023_04_cteam/assets/101164560/19634533-4fd9-477d-8c76-d6053fb9f0ff)
